name: Android CI

on:
  push:
    branches: [ main, master, dev, dev-tests ]
  pull_request:
    branches: [ main, master, dev, dev-tests ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Cache Android Emulator
        uses: actions/cache@v3
        with:
          path: |
            ~/.android/avd
            ~/.android/cache
          key: ${{ runner.os }}-android-emulator-${{ hashFiles('**/system-images/**') }}
          restore-keys: |
            ${{ runner.os }}-android-emulator-

      - name: Run instrumented tests on Android 13 (API 33)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -no-window -noaudio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest
